# Generated by Django 3.2 on 2021-05-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
